### ISSUE TITLE
Các nhóm tạo thư mục trên repo chung này

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/int3507-2016#1]
Và tạo readme mô tả tóm tắt đề tài của nhóm.

**Comment by truonganhhoang** [comment]
Nhóm nào tạo xong thì comment vào đây để tiện theo dõi.

**Comment by cuongurus** [comment]
Mỗi nhóm 1 branch khác nhau hay để master hết hả thầy?

**Comment by truonganhhoang** [comment]
Tốt nhất khi đang làm các nhóm tạo branch, khi hoàn thành một phần thì merge vào master.

**Comment by trieudh58** [comment]
Nhóm NaVi đã tạo xong folder riêng ạ. Hiện tại em không có quyền add các bạn trong nhóm em vào repo của thầy, nên em fork về repo của em và add các bạn để code trên đó. Thầy muốn check thì pull request về hay sao ạ?

**Comment by truonganhhoang** [comment]
Mình đã add tất cả các bạn là collaborators trong repo này rồi, thì em ko cần add các bạn nữa chứ?

**Comment by trieudh58** [comment]
Thưa thầy em hiểu rồi ạ. Tại vì em thấy mới có 16 watchings nên nghĩ là thầy chỉ add nhóm trưởng thôi. 😸

**Comment by truonganhhoang** [comment]
fork ra thì cùng tốt, nhưng nếu phải merge khi các em tạo pull requests nhiều thì ko ổn, vì có conflict thì mình khó tự resolve đc.. các em tự fork rồi tự merge lại.

**Comment by cuongurus** [comment]
Nhóm NSFW đã tạo folder và add mô tả về đề tài

**Comment by vantayden** [comment]
Nhóm ACE đã tạo folder, up code v0.1 với README

**Comment by namtien** [comment]
Thầy ơi giờ nhóm N2QT chủ đề ChatBot FaceBook ko được ạ ? Thầy cũng ghi rõ
2 nhóm cũng có thể trùng chủ đề .Em cảm ơn thầy

2016-09-04 22:21 GMT-07:00 vantayden notifications@github.com:

**Comment by namtien** [comment]
Nhóm N2QT đã tạo xong ạ

Vào 01:48 Ngày 05 tháng 09 năm 2016, Nam Nguyen namtiennguyen195@gmail.com
đã viết:

**Comment by fiser-khoanv11** [comment]
Nhóm Duo đã tạo folder kèm README ạ.

**Comment by tiennh-0852** [comment]
Nhóm PATH đã tạo xong forder và readme mô tả ạ !

**Comment by hientt28** [comment]
Nhóm HK đã tạo folder và add mô tả về bài toán ạ.

**Comment by cuong1995** [comment]
Thầy accept acc của em với ạ , em  chưa commit được folder lên ạ . 
Dùng lệnh git push origin master bị báo lỗi ~

**Comment by tracquangthinh** [comment]
Nhóm DTQ đã tạo folder và readme ạ

**Comment by trangnt58** [comment]
Nhóm XYZ đã tạo xong folder và readme ạ

**Comment by NguyenSiTrung** [comment]
Nhóm Dolphin đã tạo xong folder và readme ạ

**Comment by hoanggianguet** [comment]
Nhóm A2 đã tạo xong folder and readme ạ

**Comment by hongnhung95** [comment]
Dạ thưa thầy, em là thành viên nhóm N2QT, em vừa đọc được gợi ý của thầy cho một nhóm khác là có thể dùng Construct2 làm game thay bằng Angular2. Thời gian này, em có đang đi thực tập làm game 2d bằng Construct2 trong công ty và đã làm 1 số game nhỏ.Liệu em có thể xin thầy đợt báo cáo tới demo 1 game e đã làmcũng là game học vui cho các em mẫu giáo bằng construct2 oy xin thầy chuyển hướng làm game ngoại ngữ bằng Construct2 ko ạ?

**Comment by truonganhhoang** [comment]
Đc.. em và nhóm làm bằng c2 đi.

**Comment by truonganhhoang** [comment]
Mình thêm tài khoản cuong1995 rồi.

**Comment by dodv58** [comment]
Em chào thầy, hiện tại em chưa được add vào repo. Thầy add lại account của em với ạ dodv58

**Comment by truonganhhoang** [comment]
mình vừa add rồi.
