### ISSUE TITLE
Sửa lại chat bot theo hướng English learning

### ISSUE THREAD

**Issue by vantayden** [truonganhhoang/int3507-2016#103]
T sẽ code lại cấu trúc, Vương code lại các module hướng tới học tiếng Anh thông qua 4 dạng bài tập: Multichoices, translate english sentence to vietnamese và ngược lại, fill the blank.
Tuấn chỉnh sửa lại wiki của nhóm nhé!

**Comment by conlocsanco** [comment]
ok

**Comment by vuminhvuonghy** [comment]
uk
