### ISSUE TITLE
[FRIES] Tuần 8

### ISSUE THREAD

**Issue by m-inh** [truonganhhoang/int3507-2016#106]
**Update 1.x -> 2.x**

Tìm hiểu công nghệ liên quan và thực hiện update
Bổ sung tài liệu TypeScript
Công việc và hạn thực hiện được phân công trên Asana (phần mềm quản lí task nhóm)

**Comment by truonganhhoang** [comment]
Các em thực hiện quản lý việc trên github issues luôn cho tiện đánh giá.

**Comment by m-inh** [comment]
Công việc của em:
- Bổ sung tài liệu TypeScript
- Nâng cấp post editor
- Phân chia server dev và product
- Test performance cho api server

**Comment by quytm** [comment]
Trần Minh Quý:
Upgrading ứng dụng từ 1.x lên 2
- Profile

**Comment by thaibm** [comment]
Bùi Minh Thái: 
Upgrading ứng dụng từ 1.x lên 2
- Bổ sung tài liệu Upgrading
- Front page: Dynamic bar char and pie chart.

**Comment by tutv** [comment]
Trần Văn Tú:
Upgrading ứng dụng từ Angular 1 lên Angular 2
- Trang đăng nhập, đăng xuất
- Trang danh sách các lớp
- Trang sách sách các bài thảo luận
