### ISSUE TITLE
[ACE] Chuẩn bị demo, thuyết trình ngày 19/09

### ISSUE THREAD

**Issue by vantayden** [truonganhhoang/int3507-2016#14]
Hà Đức Văn: Viết cấu trúc chính chương trình, Wiki.
Lê Văn Tuấn: chuẩn bị slide thuyết trình.
Vũ Minh Vương: tìm hiểu cấu trúc tin nhắn Messenger, viết các module cho demo

**Comment by conlocsanco** [comment]
đang hoàn thành slide xong sẽ up

**Comment by vuminhvuonghy** [comment]
ok

**Comment by conlocsanco** [comment]
done!

**Comment by vuminhvuonghy** [comment]
done
