### ISSUE TITLE
Thay đổi hướng bài tập lớn

### ISSUE THREAD

**Issue by vantayden** [truonganhhoang/int3507-2016#148]
Em chào thầy.
Do bọn em nhận thấy không thể tiếp tục theo hướng phát triển chatbot hỗ trợ học tiếng anh trên messenger, nên chúng em muốn xin thầy theo lại hướng phát triển trợ lý cá nhân cho sinh viên nói riêng và người dùng nói chung. Kèm theo đó là tính năng chat ẩn danh với người lạ và tính năng chat với nhiều người lạ theo cùng sở thích.
https://www.facebook.com/chatible/ - đây là 1 page có tính năng chat với người lạ được khá nhiều người thích thú và sử dụng
http://vnreview.vn/tin-tuc-san-pham-moi/-/view_content/content/1998942/facebook-messenger-thu-nghiem-tinh-nang-tao-phong-chat-voi-nguoi-la - đây là bài viết về tính năng tạo phòng chat nhóm với người lạ cùng sở thích.
Và quan trọng hơn là em đã sửa file README ở repo cập nhật link đến bài tập của nhóm nhưng hiện tại không thấy commit cũng như file README không thấy nội dung nữa! Em đã cập nhật lại và mong thầy sắp xếp vào lịch chấm chéo của các nhóm
![Không thấy commit readme](https://cloud.githubusercontent.com/assets/19584550/20265539/36a52126-aaa4-11e6-928b-d10c9df01b1b.png)

**Comment by truonganhhoang** [comment]
ok, mình sợ thời gian ngắn quá, còn nếu các em đã chuẩn bị và demo đc vào cuối tuần này để các bạn chấm thì đổi prj của các em sang prj này.

**Comment by vantayden** [comment]
Vâng, em cảm ơn thầy
