### ISSUE TITLE
PATH demo 19/9

### ISSUE THREAD

**Issue by tiennh-0852** [truonganhhoang/int3507-2016#15]
Lê Đức Anh: Chuẩn bị source code và demo
Nguyễn Hữu Tiến + Ngô Thị Phượng: slide + thuyết trình

**Comment by ducanhk58uet** [comment]
Hoàn thiện "Hello World", connect và get data từ backend (NodeJS)

**Comment by phuongnt58** [comment]
Setup project. Chạy Hello World.

**Comment by tiennh-0852** [comment]
Chuẩn bị xong slide thuyết trình ! Đã chạy đc Hello World app

**Comment by ducanhk58uet** [comment]
**Tài liệu nghiên cứu và plan phát triển project ở đây:**
https://www.dropbox.com/s/sypclbc29lext1l/sep15-cac-van-de-hien-dai-cntt-2016.docx?dl=0

**Nội dung demo ngày 19/9:**
- Show cấu trúc project theo chuẩn M.E.A.N Stack (MongoDB, Express, Angular 2, NodeJS)
- Đăng nhập, sử dụng $http lấy dữ liệu từ server (lưu 'access_token' và 'refresh_token' xuống localStorage từ server trả về cho cơ chế xác thực OAuth 2.0)
- Hiển thị dữ liệu từ server trả về thông qua $http.get
- Bảng định tuyến (routing)
- Show API register, login

**Chuẩn bị cho buổi demo ngày 26/9:**
- Nghiên cứu angular nâng cao theo yêu cầu của thầy: **server-communication**
- Phát triển dự án (xây dựng giao diện, crawl dữ liệu, demo một bài thi trắc nghiệm).
