### ISSUE TITLE
[Thay đổi tích hợp Laravel và angular]

### ISSUE THREAD

**Issue by hientt28** [truonganhhoang/int3507-2016#150]
Dạ em chào thầy ạ,
Như đã báo cáo ban đầu nhóm em sẽ kết hợp Laravel để làm phần backend và  Angular để làm phần frontend. Tuy nhiên ,khi tích hợp angular để view giao diện thì nó rất là chậm và gặp nhiều vấn đề khó khăn . Nhóm em cũng đã hỏi nhiều anh chị trên công ty, và trên trang cộng đồng nhưng không xử lí được. Mọi người đều khuyên không nên tích hợp vào,  chỉ dùng Laravel nó sẽ nhanh hơn rất nhiều.
Vì vậy , nhóm em hiện giờ để lại frontend là blade của Laravel ạ?

**Comment by truonganhhoang** [comment]
nó chậm ở đoạn nào nhỉ? các em có debug/ đo xem đoạn nào gây ra vấn đề.

**Comment by BaoBinh95** [comment]
thưa thầy, ngay từ đầu em tích hợp nó vào, em có hỏi anh chị trên diễn đàn, và a/c trên cty thì anh chị bảo k nên chọn laravel, nhưng em lại viết hết serve là laravel rồi ạ, thầy có thể cho em dùng view blade của laravel k ạ? , ngoài ra, khi em tích hợp angular 2 + laravel hay bị crash, cái này k biết tại sao, em hỏi nhiều người trên diễn đàn cũng bảo vậy ạ. Thầy cho em đổi project dùng view của blade laravel được k ạ.
@truonganhhoang

**Comment by truonganhhoang** [comment]
ok, cuối khóa học rồi, vậy các em giới thiệu công nghệ mình sử dụng,
lavarel, view blade cho lớp vào buổi học tới nhé.

H

2016-11-17 19:40 GMT+07:00 BaoBinh95 notifications@github.com:

**Comment by BaoBinh95** [comment]
Vâng ạ, em sẽ báo cáo lại ạ, em cảm ơn thầy ah @truonganhhoang
