### ISSUE TITLE
[4C] Xin đổi bài toán của Alexa Skill

### ISSUE THREAD

**Issue by cuongpd58** [truonganhhoang/int3507-2016#172]
Em chào thầy!

Em là Phan Đoàn Cương, đại diện cho nhóm 4C xin phép thầy thay đổi bài toán cho chúng em, vì sau khi tìm hiểu kỹ thì chúng em nhận thấy bài toán thầy đưa ra cho chúng em không phù hợp với alexa. 

Bài toán mà hiện giờ thầy đưa ra cho chúng em là alexa nói ra 1 câu, user nhắc lại và alexa kiểm tra user đã nhắc lại chuẩn hay chưa. Chúng em nhận thấy bài toán không phù hợp ở chỗ:
- Mỗi speech input từ người dùng alexa sẽ hiểu là một request. Mỗi request sẽ được alexa coi là một intentRequest bao gồm thông tin về name và slots. Từ đó, chúng em rút ra được 2 điều:
+ Thứ nhất, một intentRequest KHÔNG CHỨA thông tin về text được nhận diện từ speech input của user . Và qua tìm hiểu kỹ thì alexa không cung cấp một phương thức nào trong thư viện để có thể lấy text là input của user vừa nói vào.
 + Thứ hai, khi alexa nhận được một speech input của user thì dữ liệu của input gửi thẳng về một service của alexa, alexa sẽ nhận diện và dựa vào khai báo trong SampleUtterances thì alexa sẽ biết được intentRequest của input đang trỏ đến intent nào trong skill (có trường hợp intentRequest không trỏ đến bất cứ một intent nào đã khai báo trong skill). Mà mỗi intent trong skill lại chứa một tập những câu nói đơn giản, đồng nghĩa và cùng thể hiện một request từ người dùng. Do đó, việc user nhắc lại một câu ngẫu nhiên mà alexa vừa nói sẽ dẫn đến việc speech input của người dùng không nằm trong bất cứ một intent nào trong skill, khi đó intentRequest == null và không thể xử lý tiếp được.

Với những điều trên chúng em nghĩ bài toán thầy giao cho nhóm 4C chúng em không phù hợp với alexa.

Mong thầy xem xét kỹ lưỡng giúp chúng em ạ!

**Comment by cuongdv95** [comment]
Thưa thầy, nhóm em đang định làm theo hướng sẽ để alexa nói ra 1 loạt từ cùng 1 chủ đề để học từ mới ạ. Em nghĩ là cái này sẽ phù hợp hơn vì skill alexa thường là skill đơn giản, người dùng nói và alexa trả lời yêu cầu của người dùng.

**Comment by cuongdv95** [comment]
Thưa thầy, hiện tại thì đề tài theo như thầy yêu cầu nhóm em không phù hợp để làm alexa skill. Lí do thì như bạn Cương đã trình bày ở trên.
Hiện nhóm em đã làm được 1 skill đơn giản là nói vào màu yêu thích của mình và alexa sẽ nói lại màu đó. Nhóm em dự định sẽ đưa skill này cho các bạn khác test và có thể demo vào buổi ngày mai ạ.

**Comment by truonganhhoang** [comment]
OK. Mình nghĩ vẫn có thể workaround đc. Mai sẽ trao đổi với các em cụ thể cho tiện.

**Comment by cuongdv95** [comment]
Thưa thầy, hiện tại để các nhóm khác test thì em sẽ tạm thời để cái skill nhóm em đã làm được lên được không ạ?

**Comment by truonganhhoang** [comment]
Đc. Các em làm một chương trình nhỏ là đc rồi, vì alexa này cũng phải tìm hiểu nhiều cái mới để làm.

**Comment by cuongdv95** [comment]
Vâng ạ. Em cảm ơn thầy
