### ISSUE TITLE
[PATH] thay đổi link sản phẩm

### ISSUE THREAD

**Issue by tiennh-0852** [truonganhhoang/int3507-2016#177]
@truonganhhoang 
Thưa thầy nhóm PATH chúng em đã thay đổi link sản phẩm và server đã hoạt động bình thường, mong thầy cập nhật lại trong link danh sách lớp giúp chúng em như ở github môn học ạ. Em cảm ơn !
https://docs.google.com/spreadsheets/d/1b1Gp9a83wIh5VCHXW7gYbDZNElFLCaMHgwTk7iOqcs0/edit#gid=1908105008

**Comment by truonganhhoang** [comment]
ok, mình sẽ lấy toàn bộ link, app mới nhất để chấm điểm lại.
