### ISSUE TITLE
4C - Release Alexa Skill

### ISSUE THREAD

**Issue by cuongpd58** [truonganhhoang/int3507-2016#196]
Em chào thầy,

Nhóm em đã hoàn thành skill với bài toán thầy đã giao. Chúng em mời thầy và các nhóm test theo hướng dẫn trong file Hướng dẫn test Alexa Skill.md

Em cảm ơn thầy nhiều.

**Comment by cuongdv95** [comment]
@truonganhhoang thưa thầy đây là link đến file hướng dẫn sử dụng ạ. https://github.com/truonganhhoang/int3507-2016/blob/master/4C/H%C6%B0%E1%BB%9Bng%20d%E1%BA%ABn%20test%20Alexa%20Skill.md

**Comment by truonganhhoang** [comment]
Tốt rồi. Các em bổ sung cho nhiều nhiều câu vào đc ko? Dữ liệu lấy từ 1 file text đc là tốt nhất.
