### ISSUE TITLE
[DTQ] Chuẩn bị demo ngày 19/9

### ISSUE THREAD

**Issue by tracquangthinh** [truonganhhoang/int3507-2016#23]
Tạo bot, xử lí bot với model, database: Trác Quang Thịnh
Train model: Nguyễn Thế Quân
Tạo dữ liệu câu hỏi cơ bản: Đặng Văn Đô

**Comment by quannt58** [comment]
Đang xử lý model dùng Microsoft LUIS - Language Understanding Intelligent Service
