### ISSUE TITLE
[4C Team] Chuẩn bị demo 19/09/2016

### ISSUE THREAD

**Issue by duynn1220** [truonganhhoang/int3507-2016#31]
*Phân công nhiệm vụ:

Đinh Viêt Cường: tìm hiểu ASK + tổng hợp + làm slide 
Nguyễn Ngọc Duy : Tìm hiểu về ASK là gì và 1 vài kĩ năng với ASK, tạo trang wiki và thêm nội dung
Nông Thành Công + Phan Đoàn Cương: tìm hiểu và demo

*Phân công nhiệm vụ cho các công việc tiếp theo sẽ được update tiếp tục

**Comment by duynn1220** [comment]
duy đã hoàn thành công việc và gửi bài vào facebook của nhóm

**Comment by cuongdv95** [comment]
đã hoàn thành
