### ISSUE TITLE
[4C] Nội dung báo cáo ngày 26/9 - Ứng dụng Alexa nhắc lại lời vừa nói.

### ISSUE THREAD

**Issue by congnt58** [truonganhhoang/int3507-2016#39]
- Mô tả: Người dùng nói với alexa, alexa xử lý và nhắc lại lời người dùng vừa nói bằng giọng máy.

**Comment by cuongpd58** [comment]
Thầy ơi nhóm em không tạo đc tài khoản aws  vì không có thẻ visa thầy ạ

**Comment by truonganhhoang** [comment]
Mình đã thêm tài khoản bạn Duy vào tài khoản Amazon Developer rồi.
