### ISSUE TITLE
Các nhóm viết bài giới thiệu công nghệ, kiến thức đã tìm hiểu

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/int3507-2016#4]
Các nhóm tạo trang wiki trình bày kiến thức lý thuyết đã tìm hiểu được. Nội dung về cơ bản là dịch hoặc tổng hợp và dịch tóm lược, khoảng 3-5 trang.  Ví dụ giới thiệu facebook chatbot là gì, để làm một chatbot thì làm như thế nào, và nêu một số khả năng ứng dụng của chatbot. Mục đích là để các bạn khác đọc, nắm được, và hỏi thêm trước khi trình bày, trao đổi trên lớp.

Chú ý: nhớ nêu nguồn tài liệu tham khảo.

Hạn: Thứ 2 tuần tới ngày 13/9/2016.

**Comment by trieudh58** [comment]
Thưa thầy, vậy viết wiki rồi thì có cần làm slide nữa không ạ? :smile:

**Comment by truonganhhoang** [comment]
Vẫn cần slides, cái này để đọc, cần chi tiết cụ thể hơn, slide tổng quan, ý chính, và một số chi tiết quan trọng

slides các em làm online, rồi chèn link luôn vào bài viết này.

**Comment by huyendtt195** [comment]
Thầy cho em hỏi là, tuần sau tức là mai có phải đi học không ạ? Theo như issues 1 thì đến 19/9 tức tuần sau nữa mới thuyết trình và demo sản phẩm, tuần sau thì nghỉ đúng không ạ? Tuần này chỉ cần có dealine wiki trình bày kiến thức lý thuyết đã tìm hiểu được ạ?

**Comment by truonganhhoang** [comment]
Mai vẫn nghỉ để các em chuẩn bị làm demo và báo cáo, cũng như tài liệu. Mai các nhóm PHẢI đưa tài liệu lên rồi. 

Các nhóm cũng chủ động làm demo. Buổi học tới bắt đầu chấm điểm demo rồi. 

Ở github này có phần issues, thường được dùng để quản lý công việc của từng người. Ai làm gì cần tạo issue mô tả việc sẽ làm, thỉnh thoảng cập nhật tiến độ vào issue đó, và khi xong thì đóng issue lại. Ai ko tạo issue thì có thể coi ko làm gì. Nếu chỉ cập nhật code mà ko có issue thì cũng ko được. Code các em cũng làm đến đâu thì cập nhật (push lên) đến đó.

**Comment by anhlnc** [comment]
thầy cho em hỏi là em có thể chuyến sang đề tài của công ty Sota được không ạ ?

**Comment by truonganhhoang** [comment]
Đc, các em chọn đề tài nào?

**Comment by anhlnc** [comment]
em chọn đề tài build live streaming apllication và em làm 1 người có được không ạ

**Comment by truonganhhoang** [comment]
Ok.

**Comment by cuongurus** [comment]
thầy ơi, theo em mỗi nhóm tạo issues chung assign thành viên vào, add label nhóm, add milestone theo từng tuần hoặc từng tháng, thầy có thể dễ dàng kiểm tra tiến độ cũng như công việc của từng bạn, chứ như hiện tại, lớp đông sv mà mỗi bạn tạo 1 issues thì rất nhiều, mỗi lần tạo là github lại gửi mail thông báo, em phải unsubscribe issues nào không phải nhóm hay thành viên trong nhóm cho đỡ phiền phức

**Comment by truonganhhoang** [comment]
đúng là cũng hơi phiền nhưng mình muốn bạn nào cũng biết sử dụng issue để báo cáo công việc của bản thân.. qua nhóm thì có khi có bạn ko tham gia, ko tích cực, và nhiều khi cứ bạn khác làm luôn cho. Có thể là issue theo nhóm, nhưng commit công việc thì vẫn riêng từng người.

Một số nhóm đã đưa nội dung tóm tắt lên wiki nhưng lại để nguyên tiếng Anh thì ko đc.. slides trình bày bằng tiếng Anh đc, nhưng bài viết thì phải bằng tiếng Việt, cố gắng ko dịch nguyên văn mà viết tóm tắt theo cách hiểu của các em.

**Comment by dodv58** [comment]
DTQ Link slide Facebook chatbot with LUIS
https://sway.com/E1RXO1xL3m0JUYKR
