### ISSUE TITLE
NSFW Công việc tuần này(hạn 25/9)

### ISSUE THREAD

**Issue by cuongurus** [truonganhhoang/int3507-2016#45]
# Công việc tuần này

Tạo cơ sở dữ liệu cho bot.
Tìm kiếm dữ liệu FAQ, kết nối bot với csdl.
Demo

**Comment by pmchjeukomua** [comment]
@truonganhhoang thầy ơi nhóm e nên lấy dữ liệu về phần gì

**Comment by truonganhhoang** [comment]
Bất kỳ, về angular 2 luôn xem ntn?

**Comment by pmchjeukomua** [comment]
dạ vâng
