### ISSUE TITLE
N2QT Chuẩn bị demo 19/9

### ISSUE THREAD

**Issue by namtien** [truonganhhoang/int3507-2016#5]
Nguyễn Tiến Nam,Trương Hồng Nhung : làm wiki,demo
Lê Văn Quang,Lương Thị Trang : làm slide

**Comment by hongnhung95** [comment]
Wiki đã làm xong. Nam đẩy lên github nhé!

**Comment by quangleeit** [comment]
đã tạo Issues của từng người chưa vậy

**Comment by hongnhung95** [comment]
chưa thấy ai tạo ý. chắc nhóm mình cứ tạo đi cũng được.

**Comment by namtien** [comment]
t tạo rồi sau lại đóng luôn

2016-09-12 7:07 GMT-07:00 hongnhung95 notifications@github.com:

**Comment by tranglt58** [comment]
mai có đến sớm ko hay vẫn đúng giờ.

**Comment by namtien** [comment]
có nhé ,8h30 :) .8h cũng đc rất khuyến khích

2016-09-18 9:18 GMT-07:00 tranglt58 notifications@github.com:
