### ISSUE TITLE
[DTQ] Xin dữ liệu học từ mới 

### ISSUE THREAD

**Issue by tracquangthinh** [truonganhhoang/int3507-2016#59]
Thưa thầy, nhóm DTQ bọn em đang làm chatbot học từ mới tiếng Anh nhưng gặp phải vấn đề thiếu dữ liệu học từ vựng dựa trên sách giáo khoa. Chính vì vậy mong thầy giúp đỡ hỗ trợ bọn em về mặt dữ liệu sách giáo khoa với ạ

**Comment by truonganhhoang** [comment]
Dữ liệu từ vựng ở SGK, các em có thể lấy từ sachmem.vn, chọn một cuốn sách, copy paste dữ liệu ra đc. Còn sau này cần lấy toàn bộ thì mình có thể export ra cho các em.

**Comment by NguyenThaiHoc** [comment]
@tracquangthinh dưới đây là dữ liệu mẫu 1 lớp.
[orders.txt](https://github.com/truonganhhoang/int3507-2016/files/499867/orders.txt)
