### ISSUE TITLE
[HK Team] Chuẩn bị demo 19/9/2016

### ISSUE THREAD

**Issue by hientt28** [truonganhhoang/int3507-2016#6]
Phân công công việc:
- Làm wiki và chuẩn bị source code demo: Trịnh Thị Hiền và Phạm Thị Hà
- Làm báo cáo slide để demo : Đặng Thị Khôi và Dương Thị Huế

**Comment by BaoBinh95** [comment]
Phạm Hà và Trịnh Hiền đã làm xong phần tìm hiểu tài liệu và viết trên wiki của nhóm

**Comment by BaoBinh95** [comment]
Init project, test project chạy hello world

**Comment by BaoBinh95** [comment]
Thiết kế database cho project

**Comment by BaoBinh95** [comment]
Đã tạo project angular 2 chạy helo world và chuẩn bị demo ngày 19/9.
