### ISSUE TITLE
[FRIES] Thêm đề tài tìm hiểu về Angular 2

### ISSUE THREAD

**Issue by m-inh** [truonganhhoang/int3507-2016#61]
Thưa thầy, hiện tại nhóm em vẫn đang khuyết đề tài tìm hiểu để báo cáo trên lớp về Angular 2, thầy có thể update lại Nội dung tìm hiểu Angular 2 cho nhóm em được không ạ?
Em cám ơn thầy

**Comment by truonganhhoang** [comment]
Các em chọn 2 đề tài còn lại của phần advanced nhé.
https://angular.io/docs/ts/latest/guide/ngmodule.html
