### ISSUE TITLE
[NaVi] Need help!

### ISSUE THREAD

**Issue by trieudh58** [truonganhhoang/int3507-2016#64]
Em đang gặp vấn đề như sau, mong được thầy @truonganhhoang  chỉ giúp ạ!

Đối với mỗi tin nhắn người dùng gửi cho bot, nhóm em định sử dụng học máy để phân lớp ý định người dùng, từ đó xác định người dùng muốn bot thực hiện chức năng gì.

Tương ứng với 4 chức năng, có 4 lớp như sau:
- MULTIPLE_CHOICES: làm trắc nghiệm
- NEW_WORDS: học từ mới
- LISTENING: luyện nghe
- CONVERSATION: trò chuyện thông thường với bot

Nếu là một câu để kích hoạt chức năng (VD: "tôi muốn làm trắc nghiệm", hoặc "bot ơi giúp mình học từ mới",...) thì việc phân lớp không khó lắm.
Tuy nhiên, khi một hành động đã trong quá trình của nó, thì làm thế nào để có thể phân lớp đúng đối với mỗi tin nhắn của người dùng.
Ví dụ cụ thể một đoạn hội thoại giữa bot và một người dùng như sau:
- Người dùng gửi: "làm bài tập trắc nghiệm"
- Bot gửi: 1 câu hỏi trắc nghiệm kèm đáp án (trước đó đã phân lớp được để biết chức năng cần kích hoạt là MULTIPLE_CHOICES). 
  
  Giả sử bot gửi đi câu (dạng quick reply): **Hey Nancy. We have to come back home now. Let's say .... to grandmother.**, kèm 3 đáp án: "A. goodbye", "B. hello", "C. haha"
- Người dùng gửi: "goodbye"
- Bot: ???? -> Đến đây làm sao bot nhận biết được "goodbye" là đáp án cho câu hỏi trước đó của người dùng, mà không phải là một câu thuộc phân lớp CONVERSATION?

**Comment by truonganhhoang** [comment]
Theo mình phía server các em cần lưu trạng thái người dùng, tức là vừa hỏi câu multiple choice, thì đặt trạng thái là chờ câu trả lời, và khi nhận đc msg của người dùng thì so sánh nó với đáp án để báo đúng hay sai. Nếu là 3 button người dùng phải click vào, thì encode luôn thông tin trạng thái vào trong buttons và gửi về server để server xác định ngữ cảnh đc luôn. Còn nếu là text người dùng đánh chữ goodbye vào thì phải lưu trạng thái hội thoại với người dùng đó trên server. Các em thấy như vậy có đc ko?

**Comment by trieudh58** [comment]
Thưa thầy, em đang nghĩ đến một phương án khá giống của thầy, đó là sẽ phải lưu lại ngữ cảnh giao tiếp gần nhất của bot với người dùng. Với mỗi tin nhắn đến của người dùng, chúng ta sẽ cần một query để xác định xem ngữ cảnh giao tiếp của tin nhắn trước đó của người dùng này là gì, sau đó sẽ ưu tiên đẩy tin nhắn vào controller tương ứng với ngữ cảnh đó để xử lý.

Nếu trong controller không xử lý được (vì người dùng đang muốn chuyển ngữ cảnh) thì sẽ lại back ra ngoài để thực hiện phân lớp lại đối với tin nhắn đó.

Như trong ví dụ em nêu đầu tiên, giả sử thay vì gõ "hello" thì người dùng lại gửi "học từ mới". Như vậy tin nhắn này hoàn toàn không match với bất kỳ đáp án A, B, C nào cả (dùng độ đo tương tự giữa 2 sentences). Khi đó ta sẽ chuyển tin nhắn này ra ngoài để thực hiện phân lớp lại.

Nhược điểm của cách này là với mỗi tin nhắn đến, server đều sẽ phải thực hiện 1 query để tìm ngữ cảnh giao tiếp trước đó. Do vậy em đang nghĩ là phải chuyển từ MongoDB sang Redis ạ

**Comment by truonganhhoang** [comment]
Giải pháp của em như vậy thì tốt hơn. Tuy nhiên nếu họ gõ sai chính tả, mà
mình chuyển luôn context, thì có vẻ ko hợp lý. Chọn một giải pháp làm rồi
thử nghiệm xem cái nào phù hợp và tự nhiên nhất là đc.

2016-09-28 12:30 GMT+07:00 trieudh58 notifications@github.com:

**Comment by trieudh58** [comment]
Vấn đề sai chính tả thì có thể giải quyết bằng cách đo độ tương tự giữa câu trả lời của người dùng nhập và 3 đáp án A, B, C. Nếu confidence > 80% (chẳng hạn) thì đưa ra gợi ý cho người dùng.

VD: Người dùng nhập "hellloo" => độ tương tự với đáp án "hello" sẽ đạt được một % nào đó. Nếu lớn hơn 80% thì bot đưa ra gợi ý cho người dùng: "Có phải bạn muốn lựa chọn đáp án **A. hello** không?"

Em thấy như vậy là khả thi, mặc dù implement sẽ tốn thời gian một chút 😄
