### ISSUE TITLE
[A2 Team] Chuẩn bị demo ngày 19/09/2016

### ISSUE THREAD

**Issue by hoanggianguet** [truonganhhoang/int3507-2016#7]
## Phân công công việc:
- Làm wiki và chuẩn bị sourcecode demo: Hoàng Giang, Ngụy Khắc Quân
- Chuẩn bị slide trình bày : Đào Thị Thanh Huyền và Phan Thị Thanh Hải

**Comment by huyendtt195** [comment]
- Hoàn thành xong sourcecode demo Helloworld
- Chuẩn bị xong slide thuyết trình giới thiệu Angular2
