### ISSUE TITLE
[Dolphin Team] Dolphin chuẩn bị demo 19/09/2016

### ISSUE THREAD

**Issue by NguyenSiTrung** [truonganhhoang/int3507-2016#8]
Phân công nhiệm vụ :+1: 
- Nguyễn Mạnh Cường : Tìm hiểu ứng dụng Angluar2 component cho các loại câu hỏi trắc nghiệm và tổng hợp thành word
- Hoàng Đình Tấn : cách cài đặt , làm hello world ban đầu + giới thiệu cách làm ban đầu của đề tài
- Nguyễn Sĩ Trung : Giới thiệu về Angular2 , điểm cải tiến của angular 2 so với angular 1, giới thiệu qua về đề tài
- Nguyễn Thị Yến : tạo 1 trang wiki + add nội dung (mọi người tổng hợp) + làm slide online và add link vào trang wiki

*Phân công nhiệm vụ cho các công việc tiếp theo sẽ được update tiếp tục

**Comment by NguyenSiTrung** [comment]
Trung đã hoàn thành công việc và gửi bài của mình vào trang face của nhóm ( thứ 7 ngày 12/09 )

**Comment by dinhtancg** [comment]
Tấn đã hoàn thành và gửi bài vào trang facebook nhóm vào thứ 7 ngày 12/09

**Comment by cuong1995** [comment]
Cường đã hoàn thành vào thứ 7 ngày 12/09
