### ISSUE TITLE
NSFW assignment

### ISSUE THREAD

**Issue by cuongurus** [truonganhhoang/int3507-2016#9]
# Phân công công việc 12/9/2016
- Nguyễn Duy Cường : wiki + slide + soucrce code Hello World + tìm hiểu thêm về bot framework
- Cao Hữu Đạt @datch58 , Nguyễn Trung Hoàn @pmchjeukomua : tìm hiểu các api về bóng đá phục vụ các chức năng của bot.
- Nguyễn Việt Dũng @CuLac :  tổng hợp các câu hỏi mà người dùng có thể đặt ra đối với từng chức năng( có thể là cả 1 đoạn hội thoai ) , [! important:] tổng hợp lại vào file word, các câu hỏi = tiếng anh

**Comment by datch58** [comment]
ok. t sẽ tìm hiểu và hoàn thành đúng hạn
