### ISSUE TITLE
[PATH] Công việc trong tuần tiếp theo 24/10 

### ISSUE THREAD

**Issue by ducanhk58uet** [truonganhhoang/int3507-2016#95]
- [x] Demo phần code Testing, áp dụng luôn vào project đang làm.
- [x] Chỉnh sửa lại giao diện
- [x] Thu thập dữ liệu (nên bám theo sách nào, hướng dẫn như nào...)
- [ ] Hiển thị trang thông tin người dùng.
- [x] Tạm thời bỏ phần Speaking và Writting
- [x] Deploy lên live server
- [x] Xây dựng cms đơn giản nhập dữ liệu

**Comment by ducanhk58uet** [comment]
@truonganhhoang thưa thầy, nhóm e làm 1 web về thi trắc nghiệm Tiếng Anh với các phần Nghe, Đọc, Ngữ Pháp. Và các bài trắc nghiệm làm theo từng chủ đề (hoặc level), vậy thầy có thể cho e xin ít dữ liệu được không ạ.

**Comment by truonganhhoang** [comment]
em đưa ứng dụng lên chạy đi, mình xem để biết dữ liệu cần lấy cho các em như thế nào.. hoặc các em mô tả/nói cấu trúc dữ liệu.. để mình xem và lấy dữ liệu cho đúng yêu cầu

**Comment by ducanhk58uet** [comment]
@truonganhhoang , thưa thầy, nhóm e vẫn chưa tìm được một cloud/vps nào để đưa ứng dụng lên. Thầy có thể gợi ý cho nhóm em được không ạ. 
Cấu hình app:
- Backend: NodeJS (ExpressJS)
- Frontend: Angular 2
- DB: MongoDB

**Comment by truonganhhoang** [comment]
Các em thử amazon chưa, nó cho VPS miễn phí 1 năm. Google cho 1 tháng. MS có dreamspark, giờ đổi thành imagine https://imagine.microsoft.com/
